# Form implementation generated from reading ui file 'mainwindow.ui'
# A horrific combination of machine-generated Qt boilerplate code and my encapsulated Qt objects. It's readable, but
# very long and not at all optimized.


from PyQt5 import QtCore, QtGui, QtWidgets
from Dice import Dice
from Player import Player
from PlayerLabel import PlayerLabel
from PointItem import PointItem
from ScoreCard import ScoreCard


class UiMainWindow(object):
    def setup_ui(self, main_window, player_list: list[Player]):
        main_window.setObjectName("MainWindow")
        main_window.resize(800, 580)
        main_window.setWindowIcon(QtGui.QIcon("images/game_icon.ico"))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.dice_1 = Dice(self.central_widget, QtGui.QPixmap("images/dice1.png"), 1)
        self.dice_1.setGeometry(QtCore.QRect(470, 10, 100, 100))
        self.dice_1.setText("")
        self.dice_1.setObjectName("dice_1")
        self.dice_2 = Dice(self.central_widget, QtGui.QPixmap("images/dice2.png"), 2)
        self.dice_2.setGeometry(QtCore.QRect(580, 10, 100, 100))
        self.dice_2.setText("")
        self.dice_2.setObjectName("dice_2")
        self.dice_3 = Dice(self.central_widget, QtGui.QPixmap("images/dice3.png"), 3)
        self.dice_3.setGeometry(QtCore.QRect(690, 10, 100, 100))
        self.dice_3.setText("")
        self.dice_3.setObjectName("dice_3")
        self.dice_4 = Dice(self.central_widget, QtGui.QPixmap("images/dice4.png"), 4)
        self.dice_4.setGeometry(QtCore.QRect(520, 120, 100, 100))
        self.dice_4.setText("")
        self.dice_4.setObjectName("dice_4")
        self.dice_5 = Dice(self.central_widget, QtGui.QPixmap("images/dice5.png"), 5)
        self.dice_5.setGeometry(QtCore.QRect(630, 120, 100, 100))
        self.dice_5.setText("")
        self.dice_5.setObjectName("dice_5")
        self.dice_list: list[Dice] = [self.dice_1, self.dice_2, self.dice_3, self.dice_4,
                                      self.dice_5]
        self.player_label = PlayerLabel(self.central_widget, player_list[0])
        self.player_label.setGeometry(QtCore.QRect(480, 390, 290, 140))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.player_label.setFont(font)
        self.player_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player_label.setObjectName("player_label")
        self.roll_button = QtWidgets.QPushButton(self.central_widget)
        self.roll_button.setGeometry(QtCore.QRect(480, 230, 300, 140))
        self.roll_button.setObjectName("roll_button")
        self.upper_table = ScoreCard(self.central_widget, "upper", self.dice_list, self.player_label, player_list,
                                     self.roll_button)
        self.upper_table.setGeometry(QtCore.QRect(10, 10, 450, 250))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.upper_table.setFont(font)
        self.upper_table.setRowCount(10)
        self.upper_table.setColumnCount(4)
        self.upper_table.setObjectName("upper_table")
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upper_table.setItem(9, 0, item)
        # Points items (player one, upper table)
        self.aces_player_one: PointItem = PointItem("Aces", player_list[0])
        self.upper_table.setItem(1, 2, self.aces_player_one)
        self.twos_player_one: PointItem = PointItem("Twos", player_list[0])
        self.upper_table.setItem(2, 2, self.twos_player_one)
        self.threes_player_one: PointItem = PointItem("Threes", player_list[0])
        self.upper_table.setItem(3, 2, self.threes_player_one)
        self.fours_player_one: PointItem = PointItem("Fours", player_list[0])
        self.upper_table.setItem(4, 2, self.fours_player_one)
        self.fives_player_one: PointItem = PointItem("Fives", player_list[0])
        self.upper_table.setItem(5, 2, self.fives_player_one)
        self.sixes_player_one: PointItem = PointItem("Sixes", player_list[0])
        self.upper_table.setItem(6, 2, self.sixes_player_one)
        self.total_score_player_one: PointItem = PointItem("Total Score", player_list[0])
        self.upper_table.setItem(7, 2, self.total_score_player_one)
        self.bonus_player_one: PointItem = PointItem("Bonus", player_list[0])
        self.upper_table.setItem(8, 2, self.bonus_player_one)
        self.total_player_one: PointItem = PointItem("Total", player_list[0])
        self.upper_table.setItem(9, 2, self.total_player_one)
        # Points items (player two, upper table)
        self.aces_player_two = PointItem("Aces", player_list[1])
        self.upper_table.setItem(1, 3, self.aces_player_two)
        self.twos_player_two = PointItem("Twos", player_list[1])
        self.upper_table.setItem(2, 3, self.twos_player_two)
        self.threes_player_two = PointItem("Threes", player_list[1])
        self.upper_table.setItem(3, 3, self.threes_player_two)
        self.fours_player_two = PointItem("Fours", player_list[1])
        self.upper_table.setItem(4, 3, self.fours_player_two)
        self.fives_player_two = PointItem("Fives", player_list[1])
        self.upper_table.setItem(5, 3, self.fives_player_two)
        self.sixes_player_two = PointItem("Sixes", player_list[1])
        self.upper_table.setItem(6, 3, self.sixes_player_two)
        self.total_score_player_two = PointItem("Total Score", player_list[1])
        self.upper_table.setItem(7, 3, self.total_score_player_two)
        self.bonus_player_two = PointItem("Bonus", player_list[1])
        self.upper_table.setItem(8, 3, self.bonus_player_two)
        self.total_player_two = PointItem("Total", player_list[1])
        self.upper_table.setItem(9, 3, self.total_player_two)
        self.upper_table.horizontalHeader().setVisible(False)
        self.upper_table.horizontalHeader().setDefaultSectionSize(110)
        self.upper_table.horizontalHeader().setHighlightSections(False)
        self.upper_table.horizontalHeader().setMinimumSectionSize(35)
        self.upper_table.verticalHeader().setVisible(False)
        self.upper_table.verticalHeader().setDefaultSectionSize(24)
        self.upper_table.verticalHeader().setHighlightSections(False)
        self.lower_table = ScoreCard(self.central_widget, "lower", self.dice_list, self.player_label, player_list,
                                     self.roll_button)
        self.lower_table.setGeometry(QtCore.QRect(10, 270, 450, 270))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lower_table.setFont(font)
        self.lower_table.setRowCount(11)
        self.lower_table.setColumnCount(4)
        self.lower_table.setObjectName("lower_table")
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lower_table.setItem(10, 0, item)
        # Points items (player one, lower table)
        self.three_of_a_kind_player_one = PointItem("3 of a Kind", player_list[0])
        self.lower_table.setItem(0, 2, self.three_of_a_kind_player_one)
        self.four_of_a_kind_player_one = PointItem("4 of a Kind", player_list[0])
        self.lower_table.setItem(1, 2, self.four_of_a_kind_player_one)
        self.full_house_player_one = PointItem("Full House", player_list[0])
        self.lower_table.setItem(2, 2, self.full_house_player_one)
        self.small_straight_player_one = PointItem("Small Straight", player_list[0])
        self.lower_table.setItem(3, 2, self.small_straight_player_one)
        self.large_straight_player_one = PointItem("Large Straight", player_list[0])
        self.lower_table.setItem(4, 2, self.large_straight_player_one)
        self.yahtzee_player_one = PointItem("Yahtzee", player_list[0])
        self.lower_table.setItem(5, 2, self.yahtzee_player_one)
        self.chance_player_one = PointItem("Chance", player_list[0])
        self.lower_table.setItem(6, 2, self.chance_player_one)
        self.yahtzee_bonus_player_one = PointItem("Yahtzee Bonus", player_list[0])
        self.lower_table.setItem(7, 2, self.yahtzee_bonus_player_one)
        self.total_lower_player_one = PointItem("Total (Lower)", player_list[0])
        self.lower_table.setItem(8, 2, self.total_lower_player_one)
        self.total_upper_player_one = PointItem("Total (Upper)", player_list[0])
        self.lower_table.setItem(9, 2, self.total_upper_player_one)
        self.grand_total_player_one = PointItem("Grand Total", player_list[0])
        self.lower_table.setItem(10, 2, self.grand_total_player_one)
        # Points items (player two, lower table)
        self.three_of_a_kind_player_two = PointItem("3 of a Kind", player_list[1])
        self.lower_table.setItem(0, 3, self.three_of_a_kind_player_two)
        self.four_of_a_kind_player_two = PointItem("4 of a Kind", player_list[1])
        self.lower_table.setItem(1, 3, self.four_of_a_kind_player_two)
        self.full_house_player_two = PointItem("Full House", player_list[1])
        self.lower_table.setItem(2, 3, self.full_house_player_two)
        self.small_straight_player_two = PointItem("Small Straight", player_list[1])
        self.lower_table.setItem(3, 3, self.small_straight_player_two)
        self.large_straight_player_two = PointItem("Large Straight", player_list[1])
        self.lower_table.setItem(4, 3, self.large_straight_player_two)
        self.yahtzee_player_two = PointItem("Yahtzee", player_list[1])
        self.lower_table.setItem(5, 3, self.yahtzee_player_two)
        self.chance_player_two = PointItem("Chance", player_list[1])
        self.lower_table.setItem(6, 3, self.chance_player_two)
        self.yahtzee_bonus_player_two = PointItem("Yahtzee Bonus", player_list[1])
        self.lower_table.setItem(7, 3, self.yahtzee_bonus_player_two)
        self.total_lower_player_two = PointItem("Total (Lower)", player_list[1])
        self.lower_table.setItem(8, 3, self.total_lower_player_two)
        self.total_upper_player_two = PointItem("Total (Upper)", player_list[1])
        self.lower_table.setItem(9, 3, self.total_upper_player_two)
        self.grand_total_player_two = PointItem("Grand Total", player_list[1])
        self.lower_table.setItem(10, 3, self.grand_total_player_two)
        self.lower_table.horizontalHeader().setVisible(False)
        self.lower_table.horizontalHeader().setDefaultSectionSize(110)
        self.lower_table.horizontalHeader().setHighlightSections(False)
        self.lower_table.verticalHeader().setVisible(False)
        self.lower_table.verticalHeader().setDefaultSectionSize(24)
        main_window.setCentralWidget(self.central_widget)
        self.menu = QtWidgets.QMenuBar(main_window)
        self.menu.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menu.setObjectName("menu")
        self.file_menu = QtWidgets.QMenu(self.menu)
        self.file_menu.setObjectName("file_menu")
        self.game_menu = QtWidgets.QMenu(self.menu)
        self.game_menu.setObjectName("game_menu")
        self.about_menu = QtWidgets.QMenu(self.menu)
        self.about_menu.setObjectName("about_menu")
        main_window.setMenuBar(self.menu)
        self.exit_action = QtWidgets.QAction(main_window)
        self.exit_action.setObjectName("exit_action")
        self.new_game_action = QtWidgets.QAction(main_window)
        self.new_game_action.setObjectName("new_game_action")
        self.credits_action = QtWidgets.QAction(main_window)
        self.credits_action.setObjectName("credits_action")
        self.file_menu.addAction(self.exit_action)
        self.game_menu.addAction(self.new_game_action)
        self.about_menu.addAction(self.credits_action)
        self.menu.addAction(self.file_menu.menuAction())
        self.menu.addAction(self.game_menu.menuAction())
        self.menu.addAction(self.about_menu.menuAction())
        self.total_score_player_one.set_status("selected")
        self.bonus_player_one.set_status("selected")
        self.total_player_one.set_status("selected")
        self.total_score_player_two.set_status("selected")
        self.bonus_player_two.set_status("selected")
        self.total_player_two.set_status("selected")
        self.total_lower_player_one.set_status("selected")
        self.total_upper_player_one.set_status("selected")
        self.grand_total_player_one.set_status("selected")
        self.total_lower_player_two.set_status("selected")
        self.total_upper_player_two.set_status("selected")
        self.grand_total_player_two.set_status("selected")
        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle("Yahtzee")
        __sortingEnabled = self.upper_table.isSortingEnabled()
        self.upper_table.setSortingEnabled(False)
        item = self.upper_table.item(0, 0)
        item.setText(_translate("MainWindow", "COMBOS"))
        item = self.upper_table.item(0, 1)
        item.setText(_translate("MainWindow", "SCORE"))
        item = self.upper_table.item(0, 2)
        item.setText(_translate("MainWindow", "P1"))
        item = self.upper_table.item(0, 3)
        item.setText(_translate("MainWindow", "P2"))
        item = self.upper_table.item(1, 0)
        item.setText(_translate("MainWindow", "Aces"))
        item = self.upper_table.item(1, 1)
        item.setText(_translate("MainWindow", "Add Only Aces"))
        item = self.upper_table.item(2, 0)
        item.setText(_translate("MainWindow", "Twos"))
        item = self.upper_table.item(2, 1)
        item.setText(_translate("MainWindow", "Add Only Twos"))
        item = self.upper_table.item(3, 0)
        item.setText(_translate("MainWindow", "Threes"))
        item = self.upper_table.item(3, 1)
        item.setText(_translate("MainWindow", "Add Only Threes"))
        item = self.upper_table.item(4, 0)
        item.setText(_translate("MainWindow", "Fours"))
        item = self.upper_table.item(4, 1)
        item.setText(_translate("MainWindow", "Add Only Fours"))
        item = self.upper_table.item(5, 0)
        item.setText(_translate("MainWindow", "Fives"))
        item = self.upper_table.item(5, 1)
        item.setText(_translate("MainWindow", "Add Only Fives"))
        item = self.upper_table.item(6, 0)
        item.setText(_translate("MainWindow", "Sixes"))
        item = self.upper_table.item(6, 1)
        item.setText(_translate("MainWindow", "Add Only Sixes"))
        item = self.upper_table.item(7, 0)
        item.setText(_translate("MainWindow", "Total Score"))
        item = self.upper_table.item(8, 0)
        item.setText(_translate("MainWindow", "Bonus"))
        item = self.upper_table.item(8, 1)
        item.setText(_translate("MainWindow", "If >=63, add 35"))
        item = self.upper_table.item(9, 0)
        item.setText(_translate("MainWindow", "Total"))
        self.upper_table.setSortingEnabled(False)
        self.upper_table.setEditTriggers(self.upper_table.EditTrigger.NoEditTriggers)
        self.lower_table.setSortingEnabled(False)
        item = self.lower_table.item(0, 0)
        item.setText(_translate("MainWindow", "3 of a Kind"))
        item = self.lower_table.item(0, 1)
        item.setText(_translate("MainWindow", "Add Total of Dice"))
        item = self.lower_table.item(1, 0)
        item.setText(_translate("MainWindow", "4 of a Kind"))
        item = self.lower_table.item(1, 1)
        item.setText(_translate("MainWindow", "Add Total of Dice"))
        item = self.lower_table.item(2, 0)
        item.setText(_translate("MainWindow", "Full House"))
        item = self.lower_table.item(2, 1)
        item.setText(_translate("MainWindow", "Score 25"))
        item = self.lower_table.item(3, 0)
        item.setText(_translate("MainWindow", "Sm. Straight"))
        item = self.lower_table.item(3, 1)
        item.setText(_translate("MainWindow", "Score 30"))
        item = self.lower_table.item(4, 0)
        item.setText(_translate("MainWindow", "Lg. Straight"))
        item = self.lower_table.item(4, 1)
        item.setText(_translate("MainWindow", "Score 40"))
        item = self.lower_table.item(5, 0)
        item.setText(_translate("MainWindow", "Yahtzee"))
        item = self.lower_table.item(5, 1)
        item.setText(_translate("MainWindow", "Score 50"))
        item = self.lower_table.item(6, 0)
        item.setText(_translate("MainWindow", "Chance"))
        item = self.lower_table.item(6, 1)
        item.setText(_translate("MainWindow", "Total of Five Dice"))
        item = self.lower_table.item(7, 0)
        item.setText(_translate("MainWindow", "Yahtzee Bonus"))
        item = self.lower_table.item(7, 1)
        item.setText(_translate("MainWindow", "100 per Yahtzee"))
        item = self.lower_table.item(8, 0)
        item.setText(_translate("MainWindow", "Total (Lower)"))
        item = self.lower_table.item(9, 0)
        item.setText(_translate("MainWindow", "Total (Upper)"))
        item = self.lower_table.item(10, 0)
        self.lower_table.setEditTriggers(self.lower_table.EditTrigger.NoEditTriggers)
        item.setText(_translate("MainWindow", "Grand Total"))
        self.roll_button.setText(_translate("MainWindow", "Start Game"))
        self.player_label.setText(_translate("MainWindow", "Player 1!"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.game_menu.setTitle(_translate("MainWindow", "Game"))
        self.about_menu.setTitle(_translate("MainWindow", "About"))
        self.exit_action.setText(_translate("MainWindow", "Exit"))
        self.new_game_action.setText(_translate("MainWindow", "New Game"))
        self.credits_action.setText(_translate("MainWindow", "Credits"))


class MainWindow(QtWidgets.QMainWindow, UiMainWindow):
    def __init__(self, _player_list: list[Player], *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.player_list = _player_list
        self.setup_ui(self, self.player_list)
